name: continuous-integration
on: 
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      # Run linter
      - name: Install Black
        run: pip install black
      - name: Run black in check mode
        run: black . --check 
      # Run pytests
      - name: Install pyspark-app
        run: pip install e .
      - name: Run pytest
        run: pytest